# GitLab CI build configuration file

stages:
  - test
  - review
  - documentation
  - build

before_script:
  - mkdir -p ~/.ssh
  - touch ~/.ssh/known_hosts
  - ssh-keygen -F repo.pacelink.net > /dev/null || ssh-keyscan repo.pacelink.net >> ~/.ssh/known_hosts
  - ssh-keygen -F docs.pacelink.net > /dev/null || ssh-keyscan docs.pacelink.net >> ~/.ssh/known_hosts
  - ssh-keygen -F lab.jamit.de > /dev/null || ssh-keyscan lab.jamit.de >> ~/.ssh/known_hosts
  - eval $(ssh-agent -s)
  - ssh-add # Add default key to SSH agent
  - rm -f tmpfile && echo "$SSH_PRIVATE_KEY_DEPLOYS" >tmpfile && chmod 600 tmpfile && ssh-add tmpfile && rm -f tmpfile
  - cd Framework # Change into Framework directory

after_script:
  - cd .. # Change back to root directory

code_style:
  stage: test
  script:
    - fastlane code_style
  only:
      - branches
  except:
      - master

review:
  stage: review
  script:
    - fastlane build_project
  only:
    - branches
  tags:
    - xcode-10.2

documentation:
  stage: documentation
  script:
    - fastlane documentation
    - cp -r images docs/images
    - scp -r docs/* $DOCS_ROOT/docs/cloud-sdk/ios/
  only:
    - tags
  tags:
    - xcode-10.2

library:
  stage: build
  script:
    - fastlane build_library
    - scp ../CloudSDK.framework.zip $BINARY_ROOT/cloudkit/ios/library/CloudSDK.framework_$CI_BUILD_TAG.zip
  only:
    - tags
  tags:
    - xcode-10.2
