fastlane_version "1.82.0"
default_platform :ios

platform :ios do
  desc 'Building example app'
  lane :build_example_app do
    sigh

    gym(
      project: 'CloudSDKExampleApp.xcodeproj',
      scheme: "CloudSDKExampleApp",
      export_method: "enterprise",
    )
  end
end
